// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa5YFo__zd90dIP_obqJUZtlXS91LyPns',
    appId: '1:564991418099:web:7a982e2f90ce2445736186',
    messagingSenderId: '564991418099',
    projectId: 'fir-app-c0057',
    authDomain: 'fir-app-c0057.firebaseapp.com',
    storageBucket: 'fir-app-c0057.appspot.com',
    measurementId: 'G-HGSLSYEVY5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7tipaLu90NC10WGFgLPduL_EtH4p2fgk',
    appId: '1:564991418099:android:18e8bdd1d5a87067736186',
    messagingSenderId: '564991418099',
    projectId: 'fir-app-c0057',
    storageBucket: 'fir-app-c0057.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9oEwDa2nTN5A7vafHpaKm3l8Ypo2C9fw',
    appId: '1:564991418099:ios:d43f928117e0be4a736186',
    messagingSenderId: '564991418099',
    projectId: 'fir-app-c0057',
    storageBucket: 'fir-app-c0057.appspot.com',
    iosClientId: '564991418099-um2r8ss0l74kbc8496ae8v8b49fiagcd.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9oEwDa2nTN5A7vafHpaKm3l8Ypo2C9fw',
    appId: '1:564991418099:ios:d43f928117e0be4a736186',
    messagingSenderId: '564991418099',
    projectId: 'fir-app-c0057',
    storageBucket: 'fir-app-c0057.appspot.com',
    iosClientId: '564991418099-um2r8ss0l74kbc8496ae8v8b49fiagcd.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );
}
